### ISSUE TITLE
Insufficient input validation/error handling of form data

### ISSUE THREAD

**Issue by svenhertle** [codingjoe/django-select2#78]
**Describe the bug**
django-select2 does not validate the provided form data properly, so users can trigger an internal server error. The bug seems to be located in the method `optgroups` of the class `ModelSelect2Mixin`, where a a database query is built based on the form data (line 471/472). If the form data does not have the expected data type (like string instead of an integer), Django raises a `ValueError` which is not properly handled.

**Exception & Traceback**
From the example app:

```
  Environment:
  
  
  Request Method: POST
  Request URL: http://localhost:8000/
  
  Django Version: 3.2.6
  Python Version: 3.9.2
  Installed Applications:
  ['django.contrib.admin',
   'django.contrib.auth',
   'django.contrib.contenttypes',
   'django.contrib.sessions',
   'django.contrib.messages',
   'django.contrib.staticfiles',
   'django_select2',
   'example']
  Installed Middleware:
  ['django.middleware.security.SecurityMiddleware',
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.common.CommonMiddleware',
   'django.middleware.csrf.CsrfViewMiddleware',
   'django.contrib.auth.middleware.AuthenticationMiddleware',
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.clickjacking.XFrameOptionsMiddleware']
  
  
  Template error:
  In template /home/.../django-select2/example/example/templates/example/book_form.html, error at line 14
     Field 'id' expected a number but got 'test'.
     4 :     <title>Create Book</title>
     5 :     {{ form.media.css }}
     6 :     <style>
     7 :         input, select {width: 100%}
     8 :     </style>
     9 : </head>
     10 : <body>
     11 :     <h1>Create a new Book</h1>
     12 :     <form method="POST">
     13 :         {% csrf_token %}
     14 :          {{ form.as_p }} 
     15 :         <input type="submit">
     16 :     </form>
     17 :     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     18 :     {{ form.media.js }}
     19 : </body>
     20 : </html>
     21 : 
  
  Traceback (most recent call last):
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
      return int(value)
  
  The above exception (invalid literal for int() with base 10: 'test') was the direct cause of the following exception:
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
      response = get_response(request)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
      response = response.render()
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
      self.content = self.rendered_content
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
      return template.render(context, self._request)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
      return self.template.render(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
      return self._render(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
      return self.nodelist.render(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
      bit = node.render_annotated(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
      return self.render(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 988, in render
      output = self.filter_expression.resolve(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 671, in resolve
      obj = self.var.resolve(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 796, in resolve
      value = self._resolve_lookup(context)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/template/base.py", line 858, in _resolve_lookup
      current = current()
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/forms.py", line 290, in as_p
      return self._html_output(
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/forms.py", line 227, in _html_output
      output.append(normal_row % {
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/utils/html.py", line 376, in <lambda>
      klass.__str__ = lambda self: mark_safe(klass_str(self))
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/boundfield.py", line 34, in __str__
      return self.as_widget()
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/boundfield.py", line 93, in as_widget
      return widget.render(
    File "/home/.../django-select2/django_select2/forms.py", line 264, in render
      output = super().render(*args, **kwargs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/widgets.py", line 246, in render
      context = self.get_context(name, value, attrs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/widgets.py", line 683, in get_context
      context = super().get_context(name, value, attrs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/forms/widgets.py", line 644, in get_context
      context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
    File "/home/.../django-select2/django_select2/forms.py", line 472, in optgroups
      for obj in self.choices.queryset.filter(query):
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
      return self._filter_or_exclude(False, args, kwargs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
      clone._filter_or_exclude_inplace(negate, args, kwargs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
      self._query.add_q(Q(*args, **kwargs))
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
      clause, _ = self._add_q(q_object, self.used_aliases)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
      child_clause, needed_inner = self.build_filter(
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1265, in build_filter
      return self._add_q(
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
      child_clause, needed_inner = self.build_filter(
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
      condition = self.build_lookup(lookups, col, value)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
      lookup = lookup_class(lhs, rhs)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
      self.rhs = self.get_prep_lookup()
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 240, in get_prep_lookup
      rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
    File "/home/.../django-select2/example/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
      raise e.__class__(
  
  Exception Type: ValueError at /
  Exception Value: Field 'id' expected a number but got 'test'.
```

**Code Snippet**
The example app can be used to reproduce the error.

**To Reproduce**
This screenshot shows an exemplarily HTTP request, that triggers the internal server error:
![grafik](https://user-images.githubusercontent.com/1931925/129186265-f0e3b34c-cd15-4769-9a12-eaa5edcf139c.png)
A primary key (integer) would be expected here, but a string is provided.

**Expected behavior**
Invalid data should be handled properly in the widget.

Django validates the data later on while cleaning the form. When removing the django-select2 widget, it works as expected:
![grafik](https://user-images.githubusercontent.com/1931925/129187061-16b7f98c-378d-4a46-8903-9773b6f853ee.png)

I assume that handling the `ValueError` exception is sufficient here, but I am not familiar with the django-select2 code.

**Comment by codingjoe** [comment]
Hi @svenhertle,

Thank you for reaching out. Sadly, there is no sufficient way to catch all casting errors (not only `ValueError`) that the ORM might raise and since PKs can come in any type, we can't generically validate by type.

That being said, you can always adapt the views to perform the validation suitable for your use case. If you need any pointers or have any ideas how to provide a generic solution. Please let me know.

Best,
Joe

**Comment by svenhertle** [comment]
Hi Joe,

thanks for the fast response! I agree that this is not easy to solve due to the different types of exceptions that the ORM might raise.

However, I think that validation should be done by the form and not by the widget. As long as the widget does not crash, everything works fine (tested with an exception handler around the problematic code - the invalid value is still rejected during form validation).

I assume that almost all applications using django-select2 have this issue. The example application does not perform additional validation in the view and I did not find that hint in the documentation.

I quickly reviewed the Django code that performs the form validation and I think these are the relevant exceptions:
- `ValueError`
- `TypeError`
- `ValidationError`

Best regards
Sven
